### ISSUE TITLE
can you give a compare with existing implementations?

### ISSUE THREAD

**Issue by zsz00** [JuliaMLTools/TransformerBlocks.jl#1]
I appreciate your excellent work, especially the example https://juliamltools.github.io/shakespeare-gpt

there are some existing implementations of MultiHeadAttention and Transformer: 
https://github.com/FluxML/Flux.jl/pull/2146
https://github.com/chengchingwen/NeuralAttentionlib.jl
https://github.com/chengchingwen/Transformers.jl

can you give a compare with existing implementations ?
why you want to implementation this again  ?

**Comment by JuliaMLTools** [comment]
Hello! The other version is slow and has an overly complicated interface in my opinion.

**Comment by JuliaMLTools** [comment]
TransformerBlocks.jl is intended to be minimalist and hyper-optimized for performance.
